---
title: "Optimisation"
---

## Question 1: Bisection Method

```{r}
g <- function(x) log(x)/(1+x)
curve(g(x), from = 0 , to= 5) # plotting the garph to get a rough idea of where interval wise the maximum lies 
#graph suggests between 0.5 and 1.5 

#need to find the deriv of g(if working by hand)
#need to determine initial sign change points  #can be determined from the graph
# need to make a loop where the function iterates through m until it converges to the max (while loop)
# a=0.5 and b= 1.5 as aformentioned 

```

```{r}
x=runif(10)
w=expression(log(x)/(1+x))
D(w,'x')
# the domain of the function is x>0 since x=0 is undefined
# from that we can also deduce that (1+x)^2 is always positive and so we can omit it in finding h()>0 annd h()<0 which is the derivative.

```

```{r}
h <- function(x) ((1/x)*(1+x)) - log(x)
a= 1
b=10
tolerance = 1e-7
while ((b-a)/2> tolerance) {  # set an arbitrarily small number that the interval must be greater than for this loop
  m<- (a+b)/2
  if (h(a)*h(m)<0 ){   # shows sign change so max in [a,m]
    b<-m
 }else {
    a<-m              #no sign change means max is in the other interval[m,b]
  }
}
xmax = (a+b)/2
```

```{r}
uniroot(h,lower = 1, upper = 10)
```

## Question 2 : Maximum likelihood

```{r}
counts <- c(3,1,1,3,1,4,3,2,0,5,0,4,2)

```

## Question 5 : Constrained linear Optimisation

```{r}
#generally this minimises
f<-function(m){  #expects a vector of parameters-m
   x=m[1]
   y=m[2]
   z=m[3]
  2*x+2*y+3*z
}
grr<-function(m){
  # x <-m[1]
  # y <- m[2]
  # z <- m[3]
  c(2,2,3)
}
objective_coeff<-c(2,2,3)
  
ui <-rbind(c(2,-1,-1),
           c(-4,1,-3),
           c(1,0,0),
           c(0,1,0),
           c(0,0,1))

ci <-c(-1,-3,0,0,0)
results<-constrOptim(c(0.2,0.5,0.2), f,grr,ui,ci)
# convergence result has to give zero, otherwise something went wrong
```

```{r}
optim(c(0.2,05,0.2),f) #the opimal if function was unconstrained
```
