project:
  title: "Quarto_Practice"
date: last-modified
author: "Makopoi Lejaha"
editor: visual

format:
  html:
    toc: true
    toc-title: "Contents"  # You can change this to "Questions" if you like
    theme: cosmo
execute:
  warning: false           # I left these two just to keep your 
  message: false




  #toc-depth: 3
    number-sections: true
    theme: cosmo
    code-fold: true